# Generated by Django 4.0.2 on 2022-04-17 22:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyparticipant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=(), max_length=128, region=None),
            preserve_default=False,
        ),
    ]
