# Generated by Django 4.0.2 on 2022-04-23 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyparticipant',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyparticipant',
            name='confirmed_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyparticipant',
            name='token',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='studyparticipant',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
