# Generated by Django 4.0.2 on 2022-04-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studyparticipant_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('education_level', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('hispanic_origin', models.BooleanField(default=False)),
                ('marital_status', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
