# Generated by Django 4.0.2 on 2022-04-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dataentry_alter_survey_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataentry',
            options={'verbose_name_plural': 'Data Entries'},
        ),
    ]
