# Generated by Django 4.0.2 on 2022-04-27 05:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dataentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyparticipant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
