# Generated by Django 4.0.2 on 2022-04-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_studyparticipant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyparticipant',
            name='full_name',
            field=models.CharField(default='joe t', max_length=400),
            preserve_default=False,
        ),
    ]
