# Generated by Django 4.0.2 on 2022-06-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_dataentry_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='internet_connection',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='tab_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
