# Generated by Django 4.0.2 on 2022-08-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dataentry_internet_connection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='age',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='survey',
            name='computer_use',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='household_computers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='household_members',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='internet_access',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='technology_compentency_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='hispanic_origin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
