# Generated by Django 4.0.2 on 2022-12-01 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.studyparticipant'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.survey'),
        ),
    ]
