# Generated by Django 4.0.2 on 2022-12-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_dataentry_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='participants',
            field=models.ManyToManyField(blank=True, to='api.StudyParticipant'),
        ),
    ]
