# Generated by Django 4.0.2 on 2022-12-09 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_dataentry_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresult',
            name='participant',
        ),
        migrations.AlterField(
            model_name='survey',
            name='participants',
            field=models.ManyToManyField(blank=True, to='api.StudyParticipant'),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
