# Generated by Django 4.0.2 on 2022-12-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_surveyresult_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
