# Generated by Django 4.0.2 on 2022-12-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_surveyresult_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresult',
            old_name='technology_compentency_level',
            new_name='complex_computer_level',
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='computer_acting_up_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='computer_difficulty_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='handle_computer_problems_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='solve_computer_problems_level',
            field=models.IntegerField(null=True),
        ),
    ]
