# Generated by Django 4.0.2 on 2022-12-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_technology_compentency_level_surveyresult_complex_computer_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='race',
            field=models.TextField(null=True),
        ),
    ]
