# Generated by Django 4.0.2 on 2022-12-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_surveyresult_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
