# Generated by Django 4.0.2 on 2022-12-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_survey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
