# Generated by Django 4.0.2 on 2023-01-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_survey_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyparticipant',
            name='surveys',
            field=models.ManyToManyField(to='api.Survey'),
        ),
    ]
