# Generated by Django 4.0.2 on 2023-01-05 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_studyparticipant_surveys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyparticipant',
            name='surveys',
        ),
    ]
