# Generated by Django 4.0.2 on 2023-01-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_studyparticipant_surveys'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyparticipant',
            name='surveys',
            field=models.ManyToManyField(blank=True, to='api.Survey'),
        ),
    ]
