# Generated by Django 4.0.2 on 2023-01-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_studyparticipant_surveys'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='idle_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
