# Generated by Django 4.0.2 on 2023-01-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_dataentry_idle_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyparticipant',
            name='device_serial_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
